### ISSUE TITLE
Better support for CSV in the UI

### ISSUE THREAD

**Issue by twinkarma** [GateNLP/gate-teamware#191]
Add UI to allow previewing input and output of the annotation widget as a table/csv instead of JSON

* [x] Global option to switch to viewing/using CSV or JSON
* [x] Option to select between using JSON and csv for Document input preview and Annotation output preview
* [x] Add table widget/csv text box for document input preview
* [x] Add table/csv text box for Annotation output preview  
* [x] Ability to show csv/table instead of JSON when viewing the content of documents and annotations

**Comment by davidwilby** [comment]
also see #178

**Comment by twinkarma** [comment]
Resolved in #247
