### ISSUE TITLE
Add citation details

### ISSUE THREAD

**Issue by davidwilby** [GateNLP/gate-teamware#240]
@silviavg is preparing a publication using Teamware :tada: and has asked about citation, which I absolutely encourage.

My feeling is that until such time as we have a paper describing the tool (which I would also like to do at some point) then we should add a CITATION.cff file (see https://citation-file-format.github.io/) for directly citing the software via the repository.

Any advance on that plan?

@silviavg had asked about citing the paper for the old teamware [here](https://link.springer.com/article/10.1007/s10579-013-9215-6) though I think that this would not be the right solution, since the two tools share no software lineage whatsoever. But we could also include citing this paper if that is desirable @kbontcheva @ianroberts

**Comment by ianroberts** [comment]
Suggest [registering this repo with Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) so releases get automatic DOIs.

**Comment by davidwilby** [comment]
closed by #243
