### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by twinkarma** [GateNLP/gate-teamware#241]

**Comment by davidwilby** [comment]
Add HTTP requests from teamware to an internal web server to collect:
- [ ] project creation
- [ ] country/IP address
- [ ] project type (research, commercial etc.)
- [ ] numbers of users
- [ ] numbers of documents

**Comment by ianroberts** [comment]
IP address does not need to be sent explicitly, telemetry server gets it automatically as the source IP of the ping request.

**Comment by davidwilby** [comment]
Some existing solutions for me to look into:
* https://opentelemetry.io/
* https://telemetrydeck.com/

though probably not since the free tiers are limited and we presumably want to avoid vendor lock-in

**Comment by davidwilby** [comment]
Telemetry server repo set up at [GATENLP/telemetry-server](https://github.com/GATENLP/telemetry-server)
