### ISSUE TITLE
Option to anonymize annotator identities in exports

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gate-teamware#259]
Currently all exports of annotated documents reference the annotators by their username, which will often be personally identifiable information about the annotator such as an email address.  When exporting annotations from Teamware with a view to sharing them with other people outside the immediate project team, it would be good to have the option to use a non-PII identifier instead of the annotator's username.

An obvious choice would be the user object PK or some kind of hash thereof, as this is guaranteed to be consistent, i.e. within the export you can tell which annotations were from the same person and which were from different people, but not identify who those people actually were.

**Comment by davidwilby** [comment]
Export annotator id as pk (anonymous) as default behaviour.
Export with annotator id as an optional behaviour.
