### ISSUE TITLE
Message "t.currentAnnotationTask is null" after completing last annotation

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-teamware#269]
Running on Firefox browser, completed all annotation tasks, getting shown the screen "Thank you for participating" which is fine. 

However, also get shown a small popup that contains "Could not get annotation task. t.currentAnnotationTask is null" which probably should not be shown. Can be clicked away with "x" but still ...

**Comment by twinkarma** [comment]
Fixed in #302
