### ISSUE TITLE
Order of e.g. radio button options is not preserved

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-teamware#307]
Having something like: 

```
    "type": "radio",
    "title": "Choose!",
    "options": {
      "ok": "OK",
      "ambiguous": "Ambiguous",
      "nok": "NOK - Sensitive!"
    }
```

shows a preview where the order of the radio buttons coincides with what is in the definition.

However, as soon as I save the project, the definition has the buttons in a different order which causes them to get shown in that different order as well. 

The order should be kept as this could often reflect options ordered by some kind of degree or strength ...

**Comment by ianroberts** [comment]
Not a bug - we state explicitly in the documentation that order is not guaranteed when you use the "dict" form of options, since JSON objects are by definition unordered.  If you want a predictable order then you should use the array form instead:

```json
{
    "type": "radio",
    "title": "Choose!",
    "options": [
        {"value": "ok", "label": "OK"},
        {"value": "ambiguous", "label": "Ambiguous"},
        {"value": "nok", "label": "NOK - Sensitive!"}
    ]
}
```

**Comment by johann-petrak** [comment]
Ah thanks!
It might be good to use this form in the docs as an example then, as it is probably what is wanted in most cases.

**Comment by ianroberts** [comment]
The majority of the examples from https://gatenlp.github.io/gate-teamware/development/manageradminguide/project_config.html#radio-input downwards do use the array form already.  It's only the one or two general examples at the top that don't but maybe they should be changed as well.
