### ISSUE TITLE
User marked "admin" cannot view projects when first logging in

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gate-teamware#320]
## Describe the bug
The "admin" role is supposed to imply the "manager" role, but when a user who is marked as an "admin" but not also explicitly as "manager" logs in they cannot navigate to the projects list page.  Performing a hard refresh of the page after logging in restores the expected behaviour and the user _is_ then able to view projects.

## To Reproduce
1. Sign in as a user who has the "admin" role but is not also _explicitly_ assigned the "manager" role
2. Click "projects" in the top left

## Expected behavior
Navigate to project page

## Observed behaviour
App remains on the front page

## Notes
This appears to be down to a mismatch between the logic in the RPC methods `is_authenticated` (which returns `isManager: true` when `user.is_manager or user.is_staff`) and `login` (which only checks `is_manager`).  Signing in calls `login` whereas refreshing the page when _already_ signed in calls `is_authenticated`.

**Comment by davidwilby** [comment]
Ah! I'd spotted (some) of this behaviour and failed to track down what was causing it, thanks!

**Comment by twinkarma** [comment]
Resolved with last PR
