### ISSUE TITLE
Tooltips don't show for Checkboxes in `AnnotationRendererPreview`

### ISSUE THREAD

**Issue by davidwilby** [GateNLP/gate-teamware#351]
Now that the checkbox widget component uses `b-form-checkbox-group` containing some `b-form-checkbox` components so that we can use the bootstrap vue tooltip component, there's a weird issue
in the examples shown in the docs, where the tooltip works for the radio button example but not the checkbox example. ie the `?` prompt is there, but nothing shows on hovering.

**Comment by ianroberts** [comment]
Cannot reproduce - helptext popups work fine for checkboxes on our production installation.
