### ISSUE TITLE
Floating footer covers page content

### ISSUE THREAD

**Issue by freddyheppell** [GateNLP/gate-teamware#352]
## Describe the bug
The floating footer overlaps the bottom of the page content, partially obscuring the annotation buttons and obscuring some messages.

## To Reproduce
1. Go to an annotation page that is taller than the screen and scroll to the bottom

## Expected behavior
The bottom of the text is overlapped by the footer.

## Screenshots

The message card is hidden behind the footer

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/1475568/234870873-bd6449ba-c5d4-45c7-abef-72e253d930bc.png">

## Desktop (please complete the following information):
 - OS: macOS 13.3
 - Browser: Chrome
 - Version: 112

**Comment by ianroberts** [comment]
I believe this will have been fixed by #339, but that change is not yet live in the public instances.

**Comment by davidwilby** [comment]
Thanks for the bug report @freddyheppell - we noticed this recently too in https://github.com/GateNLP/gate-teamware/issues/331 and fixed in https://github.com/GateNLP/gate-teamware/pull/339 - this should be deployed fairly soon.
