### ISSUE TITLE
Test failing sporadically (test_annotations_per_doc_not_enforced_for_training_or_test)

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gate-teamware#372]
Recently one of the Python tests in particular has been failing sporadically when run in the GitHub workflows.  The scenario for this particular test is a project with:

- 5 training, 10 test and 20 annotation documents
- 6 annotators
- 3 annotations per document
- each annotator max proportion 0.6 (i.e. no one person should be allowed to annotate more than 60% of the corpus)

The test has each annotator in turn _attempt_ to complete all 5 training, 10 test, and 20 annotation documents, and checks that

1. all 6 annotators are allowed to complete all 5 training docs and all 10 test docs
  - i.e. the 60% proportion is not applied to training or test
2. no annotator was allowed to complete _more_ than 60% (12) of the 20 annotation documents
  - i.e. the 60% _does_ apply to annotation
3. the total number of actual annotations completed on the main 20 annotation docs adds up to 60
  - three annotators per document times 20 documents
4. at least one annotator was given strictly less than 12 documents
  - this proves that the three-annotations-per-document limit trumps the 60%-per-annotator.

However the test is sporadically failing at step 3, finding that there are only 59 annotations in total instead of the expected 50.  This only fails some of the time but when it does fail it's always 59 rather than 60.

There must be some weird interaction between the way we randomise the order in which documents are handed to the annotators vs exactly how we calculate the 60% threshold - will probably need to run the test a few hundred times recording the exact order in which documents are handed out and see if we can spot any patterns.

**Comment by twinkarma** [comment]
This test is also failing sporadically, I'll investigate it in this PR together:

```
=================================== FAILURES ===================================
______________ TestProjectModel.test_get_annotator_document_score ______________

self = <backend.tests.test_models.TestProjectModel testMethod=test_get_annotator_document_score>

    def test_get_annotator_document_score(self):
        annotator = self.annotators[0]
        # No annotations == 0
        self.assertEqual(0, self.project.get_annotator_document_score(annotator, DocumentType.TEST))
    
        incorrect_data = {
            "label1": "Incorrect",
            "label2": "Incorrect"
        }
    
        # All incorrect
        for doc in self.test_docs:
            anno = Annotation.objects.create(user=annotator, document=doc)
            anno.data = incorrect_data
    
        self.assertEqual(0, self.project.get_annotator_document_score(annotator, DocumentType.TEST))
    
        # All correct
        annotator2 = self.annotators[1]
        for doc in self.test_docs:
            correct_annotation_data = {
                "label1": doc.data["gold"]["label1"]["value"],
                "label2": doc.data["gold"]["label2"]["value"],
            }
            anno = Annotation.objects.create(user=annotator2, document=doc)
            anno.data = correct_annotation_data
    
>       self.assertEqual(self.num_test_docs, self.project.get_annotator_document_score(annotator2, DocumentType.TEST))
E       AssertionError: 7 != 0

backend/tests/test_models.py:696: AssertionError
```

**Comment by ianroberts** [comment]
> There must be some weird interaction between the way we randomise the order in which documents are handed to the annotators vs exactly how we calculate the 60% threshold - will probably need to run the test a few hundred times recording the exact order in which documents are handed out and see if we can spot any patterns.

I've done some more analysis and it is indeed an artefact of the order in which the random documents are handed out.

For the test in question there are 20 documents and six annotators, with each annotator getting a maximum of 12 documents each, and the way the test runs is that one annotator does as much as they are allowed to do, then the next annotator does as much as _they_ are allowed to do, and so on.  But because the documents are handed out for annotation purely at random, it is possible for the first four annotators to be given (in some random order) documents entirely from a smaller subset of the available corpus, e.g. one of my test runs assigned the first four annotators the following documents:

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
✔️ | ✔️ | ✔️ |   |   | ✔️ | ✔️ | ✔️ | ✔️ |   |   | ✔️ |   | ✔️ |   |   | ✔️ | ✔️ | ✔️ |  
✔️ | ✔️ |   | ✔️ | ✔️ |   |   | ✔️ | ✔️ |   |   | ✔️ | ✔️ | ✔️ |   |   | ✔️ | ✔️ |   | ✔️
✔️ | ✔️ |   | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   | ✔️ | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   | ✔️ |  
  |   | ✔️ | ✔️ |   |   | ✔️ |   | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   | ✔️ | ✔️ | ✔️ | ✔️ | ✔️

Note in particular document 15 has had _no_ annotators so far, and since there are only two remaining annotators available to be assigned to it, then from this point on with this set of annotators there is no possible assignment of annotators to documents that would allow the whole project to be completed.

Admittedly this is a somewhat contrived setup, in a real project you would expect your annotators to be proceeding in parallel rather than first one doing everything, then the next, etc. but it _is_ a valid use case.

As for how to fix it, one possibility could be that rather than select a document at random from across the whole corpus (minus those documents that are already fully annotated), instead first group the documents by their number of completed annotations and then select at random only from the group with the smallest number of completed annotations at this point.  In other words, make the goal of the assignment logic be to aim for as even as possible a spread of annotators across documents at every point in the annotation process.

**Comment by ianroberts** [comment]
I've implemented this now and it actually works too well!  The allocator spreads out the documents so perfectly that the first five annotators between them receive the full 12 documents each, meaning there are no documents left for annotator six:

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
✔️ |   | ✔️ | ✔️ |   |   | ✔️ |   |   |   | ✔️ |   |   | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️
✔️ | ✔️ |   |   | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   |   |   |  
  | ✔️ |   | ✔️ | ✔️ |   |   | ✔️ | ✔️ | ✔️ |   | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   | ✔️ | ✔️
✔️ |   | ✔️ |   | ✔️ | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   | ✔️ |   |   | ✔️ | ✔️ | ✔️ |   | ✔️
  | ✔️ | ✔️ | ✔️ |   | ✔️ |   |   | ✔️ |   | ✔️ | ✔️ |   | ✔️ | ✔️ |   | ✔️ | ✔️ | ✔️ |  

This is consistent every run, the first five annotators get 12 documents each (a different 12 each time) and the sixth annotator gets nothing.
