### ISSUE TITLE
Navbar warning

### ISSUE THREAD

**Issue by twinkarma** [GateNLP/gate-teamware#373]
I'm getting this warning when inspecting the site with the in-browser js console:

```
[Vue warn]: Invalid prop: type check failed for prop "small". Expected Boolean, got String with value "true".

found in

---> <Navbar> at /home/twin/gate-teamware/frontend/src/components/navbar.vue
       <AnnotationApp> at /home/twin/gate-teamware/frontend/src/AnnotationApp.vue
         <Root>
```

**Comment by davidwilby** [comment]
Resolved by #376 

Can we introduce some checking for JS console warnings/errors in cypress?

**Comment by twinkarma** [comment]
@davidwilby from my brief search there doesn't seem to be a global option that allows us to do this check unfortunately.

**Comment by twinkarma** [comment]
Merged into dev
