### ISSUE TITLE
Problems when running from inside a git repo 

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-teamware#378]
Apparently, running teamware from inside an unrelated git repo can cause problems. This should not happen as having scripts for doing this might well be part of some NLP-project in a git repo. 

In my case, the problem was that the db password for the "gate" user was considered to be wrong. So the error is rather surprising and people may not consider being inside the git repo as the cause at all. 

Also and possibly related, having certain environment variables set could cause troubles. This should also be avoided, unless the env variable starts with TEAMWARE_ or similar. All other env variabels which could cause trouble should get unset in the scripts used (or a script to do that and which should be the recommended way to do things should get created).

**Comment by twinkarma** [comment]
Thanks for reporting this @johann-petrak . Can I get more details on this?

- Are you running the app through docker or on top of conda/virtualenv?
- Are you trying to launch the app from outside of the repository's folder?
- And does it still run properly when you move down into this repository's folder running it from there instead?

Also agree that we should revisit how our environment variables are named and managed. I think prefixing everything with `TEAMWARE_` is a good idea.

**Comment by johann-petrak** [comment]
I installed teamware using the download get-teamware.sh script on March 5th 2023 script and then followed the installation steps, starting with `docker compose up`. Unfortunately I cannot remember much about this any more, only that @ianroberts  helped me with finding the problem and the solution back than was to move out of the git repo. 
So I did it all outside, both the original generation of the yml file via get-teamware.sh and starting teamwire which worked.

With this issue I just wanted to make sure that this is not forgotten if it has not been addressed in the meantime. @ianroberts  probably knows more about what might be going on?

**Comment by ianroberts** [comment]
I think we established in https://github.com/GateNLP/gate-teamware/issues/401#issuecomment-1988415607 that the problem wasn't specifically to do with running in a git repo, it was with trying to create a new teamware stack in a directory with the _same basename_ as one where you had previously created a different installation, so the new install was picking up the existing persistent volume for postgresql, which already had an existing database that had been created with a different password from the one now in `.env`.
