### ISSUE TITLE
Project search is case sensitive

### ISSUE THREAD

**Issue by freddyheppell** [GateNLP/gate-teamware#405]
## Describe the bug
Searching the list of projects is case-sensitive. This makes searching difficult if you're not sure of the exact name of the project, e.g. searching "narrative" will work if the project is called "Tweet narrative" but not "Tweet Narrative" or "Narrative of Politician Tweets" etc...

## To Reproduce
1. Create a project called "My Project"
2. Search "My project"

## Expected behavior
Results will be returned regardless of case

## Additional context
The RPC backend uses `.filter(name__contains=filters.strip())` to handle searching. Per the [Django docs](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#icontains) this can be changed to `.filter(name__icontains=filters.strip())`.

**Comment by ianroberts** [comment]
Sounds like a sensible change, feel free to submit a PR.

**Comment by ianroberts** [comment]
Thanks for the PR, this issue should close automatically when we merge dev to master to make the next release.
